services:

  postgres:
    image: postgres:18
    container_name: employee-postgres

    environment:
      POSTGRES_DB: employee_db
      POSTGRES_USER: employee_user
      POSTGRES_PASSWORD: employee_password

    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U employee_user -d employee_db
      interval: 10s
      timeout: 5s
      retries: 5

    volumes:
      - postgres_data:/var/lib/postgresql

    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: employee-backend

    restart: unless-stopped

    environment:
      DATABASE_URL: postgresql://employee_user:employee_password@postgres:5432/employee_db

    ports:
      - "8000:8000"

    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

      args:
        VITE_API_URL: http://100.48.210.159:8000

    container_name: employee-frontend

    restart: unless-stopped

    ports:
      - "5173:80"

    depends_on:
      - backend

volumes:
  postgres_data: